---
title: "State of the Child Report Region 5"
description: |
  Analysis of systems and outcomes impacting children and families in the Antelope Valley. Report was commissioned by Childrens Bureau of Southern California.
author:
  - name: Catalyst California
    url: catalystcalifornia.org
date: 2024-02-21
categories:
  - Region 5
output:
  distill::distill_article:
    css: css_theme.css
    self_contained: false
preview: images/av_beststart_logo.png
---

The Best Start Region 5 State of the Child Report represents the most comprehensive analysis of data from the region to date, consolidating data on children, families and systems in the Antelope Valley. Children’s Bureau of Southern California commissioned this report to understand the state of children in the Antelope Valley, identify indicators to monitor, and increase the amount of data available to advocates. 

You can view and download the report in its entirety [here](https://www.all4kids.org/wp-content/uploads/2023/08/Region5_StateOfTheChildReport_2023_Final_Web2-1.pdf).

The report finds that:

* [**The family-friendly, low-cost-living in the Antelope Valley, that residents love and depend on, is disappearing and a new, more proactive infrastructure for children and families is needed.**](https://www.racecounts.org/palmdale-once-affordable-for-families/) The current infrastructure was not established for the population increases the Antelope Valley has experienced in the last decade, and the lack of resources is a driver for school-to-prison, youth-to-houselessness pipelines, and other avoidable outcomes. To be specific: 

* Antelope Valley has a large, diverse, and growing population with roughly 120,000 children under the age of eighteen and 30,000 children under age 5, including many children who need extra support.
* Half of the households in and around the neighborhoods of Lancaster and Palmdale cannot cover basic costs like housing, food, transportation, and child care with their incomes, and four in five families with children under the age of six earn less than the real cost of living.
* High housing costs and lower wages contribute to a growing unhoused population in the region. Resources available in the Antelope Valley are not keeping up with the needs of the residents. Residents struggle to access health and mental health services and there are few child care and learning opportunities for their children.
* Equitable treatment of local children and families is a concern. Rates of hate crimes exceed those countywide, and law enforcement is known to both stop Black drivers and injure Black civilians more than people of other races.
* High School graduation rates in Antelope Valley schools are lower than those countywide. School administration and the teacher workforce are not representative of the diversity within the student body. Foster students and students with disabilities – students who may need the most support – are most likely to be suspended from school.
* To address these ongoing issues, increased investments in health and mental health are needed, as are increases in child care reimbursement rates and other forms of investments in education within the region. Strengthening the safety net of programs which provide resources or training to residents is a must. Individuals can collaborate to hold systems accountable and spread awareness of resources as well.
