---
title: "Frequenty Asked Questions"
author:
  - name: Catalyst California
    url: catalystcalifornia.org
output:
  distill::distill_article:
    css: css_theme.css
    self_contained: false
    toc: yes
    toc_depth: '2'
---

# How to navigate this site

Navigating the site can be done in multiple ways. A list of all of the resources contained within the site can be found on the home page of the website, along with the date that the resource was added to the site. To directly search for the data or resource you are looking for, you can use the search bar located at the top left corner of the site and type in what you are looking for. 

The "Categories" section located on the right side of the home page also contains all of the site's contents grouped by categories. For example, all previous learning dialogue presentations on the site are categorized as "Learning dialogue." Clicking on "Learning dialogue" under the "Categories" section will take you to all of the previous learning dialogue presentations.  

The current categories on the site are:

Category | Description
------------- | -------------
Analysis | Requested exploratory research and analysis on specific topics. Includes research requests from other First 5 LA departments.
Data Narrative | The Data Narrative wordpress page, which contains qualitative interview findings from Regional Network Grantees and First 5 LA Program Officers, as well as data framing and analysis to understand essential workers in Best Start geographies from 2019 - 2022.
Indicators | Any analysis of indicators related to children age 0 to 5 which are updated on a semi-regular basis by Catalyst California.
Region 1-5 | Each Region has its own category. Here you can find any Region specific reports or deliverables.
Region 1-5 | Each Region has its own category. Here you can find any Region specific reports or deliverables.

# What are the data sources on this site

The data on this site are from a variety of sources that grow and change as new data are added and updates are made. The US [Census Bureau’s American Community Survey](https://www.census.gov/programs-surveys/acs) is the data source for most of the demographic data about households with children under 5, whether by summary tables or public use microdata. [United Ways of California](https://unitedwaysca.org/realcost/) provides the data on the real cost of living in California, and the [California Department of Public Health](https://data.chhs.ca.gov/) is the source of the infant death data. See individual posts for their data sources, generally listed on or below charts.

# Where can I find more data

The data on this site are a small fraction of the data provided by their sources. Here are some data sources where you can learn more about households with children under 5, whether by direct download or contracting for special cuts of data:

* American Institutes for Research [Early Learning Needs Assessment Tool](https://elneedsassessment.org/)
* [California Health Interview Survey](https://ask.chis.ucla.edu/ask/SitePages/AskChisLogin.aspx?ReturnUrl=%2fAskCHIS%2ftools%2f_layouts%2fAuthenticate.aspx%3fSource%3d%252FAskCHIS%252Ftools%252F%255Flayouts%252FAskChisTool%252Fhome%252Easpx&Source=%2FAskCHIS%2Ftools%2F%5Flayouts%2FAskChisTool%2Fhome%2Easpx)
* California Child Care Resource and Referral Network [Child Care Data Tool](https://rrnetwork.org/research/child-care-data-tool#!0)
* California Department of Social Services [Community Care Licensing Division](https://www.ccld.dss.ca.gov/carefacilitysearch/)
* [Kidsdata.org](https://www.kidsdata.org/?site=full)
* [LA County Health Survey](http://www.publichealth.lacounty.gov/ha/hasurveyintro.htm)
* PHFE WIC [WIC Data for LA County](http://www.publichealth.lacounty.gov/ha/hasurveyintro.htm)

# What is SWANA

SWANA is an acronym that stands for Southwest Asian, or North African, which includes people of Southwest Asian or North African (SWANA), or Middle Eastern or North African (MENA), descent. Southwest Asian or North African is an alternative term to the acronym MENA, which is also commonly used in the data disaggregation of Middle Eastern groups. 

It is important to note that consensus on the identity groups included in the terms SWANA or MENA is still being built. These labels are attempts to distinguish the distinct experiences of these communities from the White experience in the United States, the group they have traditionally been folded into when it comes to data. These groups encompass a diversity of origins and intersections between national, geopolitical, religious, and ethnic identities. For years, advocacy organizations representing these communities have advocated for the inclusion of a MENA category in the U.S Census. While the U.S. Census Bureau still delays in including MENA in data collection, our proxy estimates are the best available to further disaggregate data and shed light on the unique and lived experiences of these groups.

We estimate the number of people who identify as SWANA by summing the number of people who reported any SWANA ancestry. We define SWANA ancestry based on the following categories: Afghan, Algerian, Arab, Assyrian, Bahraini, Chaldean, Egyptian, Emirati, Iranian, Iraqi, Israeli, Jordanian, Kurdish, Kuwaiti, Lebanese, Libyan, Middle Eastern, Moroccan, North African, Omani, Palestinian, Qatari, Saudi, Sudanese, Syrian, Tunisian, Turkish, Yazidi, and Yemeni. Note that these are labels and terms used by the U.S. Census Bureau, which may not reflect more inclusive and preferred terms by these groups. This list is also not exhaustive and likely will continue to change. For instance, our estimates currently do not include people who identify as Armenian though this is a group that crosses national origins that are often included in SWANA. This list is also limited by census data collection. Some groups not included in the data are Amazigh, Copts, Druze, and Bedouin.
